### ISSUE TITLE
Game crashes when taking out the Glasscutter

### ISSUE THREAD

**Issue by ZannCoelz** [kd8lvt/exclusionzone#3]
I was testing out this mod and took the Glasscutter item from the creative menu into my inventory and the game immedietly crashed.

I got two crash reports from this:
[crash-2024-06-26_20.25.46-server.txt](https://github.com/user-attachments/files/15992871/crash-2024-06-26_20.25.46-server.txt)

[crash-2024-06-26_20.25.49-client.txt](https://github.com/user-attachments/files/15992873/crash-2024-06-26_20.25.49-client.txt)

**Comment by kd8lvt** [comment]
Yeah, I encountered this yesterday - should be a fairly simple fix, just didn't have time today to fix it.
Should be done tomorrow or the day after

**Comment by HacoKavanah** [comment]
Hey, got this same crash. Any idea when this will be fixed? <3

**Comment by kd8lvt** [comment]
Sorry about the delayed response D: I saw the comment and thought "Oh yeah I need to work on that some more" and then did, instead of... y'know, replying...
It's a surprisingly difficult issue that I unfortunately haven't had a ton of time to work on.

For the time being, crafting the glasscutter instead of pulling from creative *should* prevent the issue. I think.

**Comment by kd8lvt** [comment]
Closed by above commit. Will be released on Modrinth when I figure out why potions aren't registering properly.
